### ISSUE TITLE
Unable to migrate

### ISSUE THREAD

**Issue by Bishalsingh** [mesaugat/express-api-es6-starter#1]
Getting this error while running 
npm run migrate:latest

Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

**Comment by mesaugat** [comment]
@Bishalsingh This seems to me like a database connection issue. Is your PostgreSQL server running on port 5432?

**Comment by mesaugat** [comment]
You also need to create a database first before running the migrations. I forgot to add that step in the README.

**Comment by Bishalsingh** [comment]
i am using mysql and yeah i already created database and also phpmyadmin is running

**Comment by mesaugat** [comment]
In that case you'll have to update your DB_PORT in the`.env` file.
```
DB_PORT='3306'
```
I seem to have missed it. `5432` is for PostgreSQL

**Comment by Bishalsingh** [comment]
@mesaugat thanks. i too missed the default port of mysql. btw your template is awesome man.

**Comment by mesaugat** [comment]
I've been using this template for many projects. I'll update the missing information in the docs pretty soon. Thanks.
