### ISSUE TITLE
Swagger info as yml

### ISSUE THREAD

**Issue by squgeim** [mesaugat/express-api-es6-starter#10]
Why are the swagger info in `src/docs` as jsdoc? Why not just use yaml? Wouldn't that be simpler and easier to write?

**Comment by mesaugat** [comment]
Yes, we need to do that. Current implementation is not good because we are using `swagger-jsdoc` and not `swagger-node`. We need to change so that we can use just `YAML`.

**Comment by mesaugat** [comment]
@squgeim Mind sending in a pull request?

**Comment by squgeim** [comment]
Will do.
