### ISSUE TITLE
New Migrate

### ISSUE THREAD

**Issue by duard** [mesaugat/express-api-es6-starter#17]
What is the way to generate ES6 migrations from knex ?
I try to create a new migration but it looks diferent 
```
**knex migrate:make usuarios** 

exports.up = function(knex, Promise) {
  
};

exports.down = function(knex, Promise) {
  
};

```

**Comment by mesaugat** [comment]
There is no way to generate ES6 migrations from knex. You'll have to create a generator yourself.

I would simply change those two lines.

```js
export function up(knex) {

};

export function down(knex) {

};
```

**Comment by duard** [comment]
Thanks !
