### ISSUE TITLE
help with idAttribute

### ISSUE THREAD

**Issue by duard** [mesaugat/express-api-es6-starter#21]
How can I set diferent idAttribute to my table ? 

something like   this.idAttribute: 'cpf';

**Comment by mesaugat** [comment]
Setting a different idAttribute is generally a bad idea. You can simply create another column which contains unique values and leave the `idAttribute` as it is.

Something like this should work but it might have it's consequences.

```js
class User extends bookshelf.Model {
  get tableName() {
    return TABLE_NAME;
  }

  get idAttribute() {
    return 'cpf';
  }
}
```

**Comment by duard** [comment]
I try this yesterday  and not work for me 
Do you sugest I mantain the column id and set unique to CPF ?

```
  get idAttribute() {
    return 'cpf';
  }
```

**Comment by mesaugat** [comment]
Yes that is the way to do it.
