### ISSUE TITLE
2 more fields returning

### ISSUE THREAD

**Issue by duard** [mesaugat/express-api-es6-starter#25]
After a post, the return shows 2 more fields, what is that ? I dont have that fields in my model
{
    "data": {
        "descricao": "Estamos cadastrando um registro",
        "big": "132165484655456",
        "updated_at": "2017-12-16T11:11:28.363Z",
        "created_at": "2017-12-16T11:11:28.363Z",
        "id": 1,
        **"createdAt": "2017-12-16T08:11:28.000Z",
        "updatedAt": "2017-12-16T08:11:28.000Z"**
    }
}

here is my migration

```
/**
 * Create tipos_medicamentos table.
 *
 * @param  {object} knex
 * @return {Promise}
 */
export function up(knex) {
  return knex.schema.createTable('tipos_medicamentos', table => {
    table.increments();
    table
      .timestamp('created_at')
      .notNull()
      .defaultTo(knex.raw('now()'));
    table.timestamp('updated_at').notNull();
    table.string('descricao', 255).notNull();
    table.string('big', 255);
  });
}

/**
 * Drop tipos_medicamentos table.
 *
 * @param  {object} knex
 * @return {Promise}
 */
export function down(knex) {
  return knex.schema.dropTable('tipos_medicamentos');
}

```

**Comment by mesaugat** [comment]
If your model has these lines https://github.com/mesaugat/express-api-es6-starter/blob/master/src/models/user.js#L13-L15

It will add a `created_at` and `updated_at` column to your table. Thus, it returns those fields.

**Comment by duard** [comment]
@mesaugat when I create my migration, I put

```
 table
      .timestamp('created_at')
      .notNull()
      .defaultTo(knex.raw('now()'));
    table.timestamp('updated_at').notNull();
```

and if I set timestamps(true) in my model some thing duplicate the return of createrecord with this other two columns ... but createdAt and updatedAt dont exists in my table.

**Comment by mesaugat** [comment]
Sorry, can you explain it a bit further? I am not getting you.

**Comment by duard** [comment]
I just dont understand why the return of createrecord show 4 fields related to timestamps : 

{
"data": {
"descricao": "Estamos cadastrando um registro",
"big": "132165484655456",
**"updated_at": "2017-12-16T11:11:28.363Z",
"created_at": "2017-12-16T11:11:28.363Z",**
"id": 1,
**"createdAt": "2017-12-16T08:11:28.000Z",
"updatedAt": "2017-12-16T08:11:28.000Z"**
}
}

The fields in my table are updated_at and created_at ... I dont have this createdAt and updatedAt .

I know that is somthing about :

```
  get hasTimestamps() {
    return true;
  }
```

**Comment by mesaugat** [comment]
I am not sure. Have you checked your table? I see different timestamps for each of those keys. That should mean you have different columns in your table. Try without `get hasTimestamps()` if you want to manually return `created_at` and `updated_at`

**Comment by duard** [comment]
I just follow your USER migration and model example.
