### ISSUE TITLE
How to connect with mongodb in this setup?

### ISSUE THREAD

**Issue by saleemnasa** [mesaugat/express-api-es6-starter#37]
Hi Thanks for the whole setup. 

but I am not able to connect to mongodb with this.

Please help

**Comment by mesaugat** [comment]
In `db.js` use the `mongodb` driver to connect to a MongoDB server. If you want to use some kind of object modeling for MongoDB use `mongoose`.

MongoDB: https://www.npmjs.com/package/mongodb#connect-to-mongodb
Mongoose: https://mongoosejs.com/

**Comment by mesaugat** [comment]
@saleemnasa 

This starter kit is for users who want to use relational databases. However, you can swap out some of the code in `db.js`, `models` in order to make it work with MongoDB.
