### ISSUE TITLE
Debug issue

### ISSUE THREAD

**Issue by victor-a-rigacci** [mesaugat/express-api-es6-starter#49]
Hi, first of all, excellent work!

I have a little issue, when you are debugging and save the code nodemon restart correctly but with the same version, this is because its no compiled again, only in the first run, its any way to achive that? i try diffents ways but im stuck.

Thanks!

**Comment by mesaugat** [comment]
Hello @victor-a-rigacci Did you try the legacy watch `nodemon -L` option? I'm not too sure but it maybe a nodemon issue. 

You could use something like https://github.com/kimmobrunfeldt/chokidar-cli if nodemon doesn't work.
