### ISSUE TITLE
Logger timestamp issue

### ISSUE THREAD

**Issue by pratishshr** [mesaugat/express-api-es6-starter#6]
- Date().toLocaleTimeString() doesn't seem to be working in winston

Observed behaviour:
![image](https://cloud.githubusercontent.com/assets/13301510/25861012/33e62f18-3503-11e7-8982-4b43c55ae3da.png)

Expected behaviour:
![image](https://cloud.githubusercontent.com/assets/13301510/25861039/446453e2-3503-11e7-9900-9a6b9e8a1282.png)

**Comment by mesaugat** [comment]
Where's the date? I only see time.

**Comment by mesaugat** [comment]
We are using `toLocaleTimeString()`. Maybe we shouldn't be doing that.

**Comment by pratishshr** [comment]
how about toLocaleString()

**Comment by mesaugat** [comment]
Yep

**Comment by pratishshr** [comment]
Well the tests seem to be failing.

**Comment by mesaugat** [comment]
This is why: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions. I am using environment variables in Travis.

```
A pull request sent from a fork of the upstream repository could be manipulated to expose any environment variables. The upstream repository’s maintainer would have no protection against this attack, as pull requests can be sent by anyone with a fork.
```

Thus, it's failing.
