### ISSUE TITLE
Create an auth module using JWT

### ISSUE THREAD

**Issue by mesaugat** [mesaugat/express-api-es6-starter#8]

**Comment by duard** [comment]
What about authentication using Passport and JWT ?

**Comment by mesaugat** [comment]
I've already made some progress on that without using Passport. I just want to make a simple JWT authentication module. Anyone who wants to use Passport can then make changes as they want to.

**Comment by duard** [comment]
Could you merge the implementation of JWT to us ? I would like to see it.

**Comment by mesaugat** [comment]
But it should take some time. I don't have the time right now. I did it a few months back and need to look into it before merging.

**Comment by duard** [comment]
Ok,  if you want, you could just share the code on gists.github.com

**Comment by mesaugat** [comment]
I've pushed some changes in the [auth](https://github.com/mesaugat/express-api-es6-starter/tree/auth) branch. Not sure if it works now but you can have a look. I'll try to do finish this in a few weeks.

**Comment by duard** [comment]
I'm trying to use yout auth functions ... how can I wait this Promise crypt.hash in my model ?

my User model : 
```
  initialize() {
    this.on('creating', this.hashPassword);
  }
  hashPassword() {
    let pass = this.get('password');
    console.log(`Password Criptografado ${JSON.stringify(pass)}`);
    crypt.hash(pass).then(hash => {
      this.set('password', hash);
    })
  } 
```

**Comment by duard** [comment]
I change Utils crypt.has to
```
 hash(string) {
    let saltRounds = parseInt(process.env.AUTH_SALT_ROUNDS);
    const newPass = bcrypt.hashSync(string, saltRounds);
    console.log(`SALTS => ${saltRounds} ${string} ${newPass}`);
    return newPass
  },
```
and in my model 

```
  hashPassword() {
    let pass = this.get('password');
    console.log(`Password Criptografado ${JSON.stringify(pass)}`);
    let newPass = crypt.hash(pass);
    console.log(`===> ${newPass}`);
    this.set('password', newPass);
  }

```
now it works;

**Comment by mesaugat** [comment]
It returns a Promise, you'll have to await or return `bcrypt.hashSync` as you have done.

**Comment by mesaugat** [comment]
Out of scope right now.
